<?php

namespace Ainnomix\EntityManager\Ui\DataProvider\EntityType\Form;

use Magento\Eav\Model\ResourceModel\Entity\Type\CollectionFactory;
use Magento\Ui\Component\Form\Fieldset;
use Magento\Ui\DataProvider\AbstractDataProvider;

class EntityTypeDataProvider extends AbstractDataProvider
{

    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        CollectionFactory $collectionFactory,
        array $meta = [],
        array $data = []
    ) {
        $this->collection = $collectionFactory->create();

        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
    }

    public function getMeta()
    {
        $meta = parent::getMeta();
        $meta['main']['arguments']['data']['config']['componentType'] = Fieldset::NAME;
        $meta['main']['arguments']['data']['config']['label'] = __('Main Information');
        $meta['main']['arguments']['data']['config']['collapsible'] = true;
        $meta['main']['arguments']['data']['config']['dataScope'] = 'data.entity_type';
        $meta['main']['arguments']['data']['config']['sortOrder'] = 10;
        $meta['main']['children'] = [
            'container_name' => [
                'arguments' => [
                    'data' => [
                        'config' => [
                            'formElement' => 'container',
                            'componentType' => 'container',
                            'label' => __('Entity Type Name'),
                            'required' => 1,
                            'sortOrder' => 10
                        ]
                    ]
                ],
                'children' => [
                    'name' => [
                        'arguments' => [
                            'data' => [
                                'config' => [
                                    'dataType' => 'text',
                                    'formElement' => 'input',
                                    'visible' => 1,
                                    'required' => 1,
                                    'label' => __('Entity Type Name'),
                                    'code' => 'name',
                                    'source' => 'main',
                                    'componentType' => 'field',
                                ]
                            ]
                        ]
                    ]
                ]
            ],
            'container_type' => [
                'arguments' => [
                    'data' => [
                        'config' => [
                            'formElement' => 'container',
                            'componentType' => 'container',
                            'label' => __('Entity Type Code'),
                            'required' => 1,
                            'sortOrder' => 20
                        ]
                    ]
                ],
                'children' => [
                    'type' => [
                        'arguments' => [
                            'data' => [
                                'config' => [
                                    'dataType' => 'text',
                                    'formElement' => 'input',
                                    'visible' => 1,
                                    'required' => 1,
                                    'label' => __('Entity Type Code'),
                                    'code' => 'code',
                                    'source' => 'main',
                                    'componentType' => 'field',
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ];

        return $meta;
    }
    
    public function getData()
    {
        $item = $this->getCollection()->getData();
        return $item;
        return parent::getData(); // TODO: Change the autogenerated stub
    }
}
